### ISSUE TITLE
Add upload complete message

### ISSUE THREAD

**Issue by dipayan1985** [ebi-ait/sars-cov2-data-upload#11]

**Comment by mcourtot** [comment]
something like https://chemicloud.com/kb/storage/2017/03/File-Manager-Upload-Complete-1024x545.png maybe?

**Comment by dipayan1985** [comment]
![snip-progress-bar](https://user-images.githubusercontent.com/55179939/81313006-37d25900-907f-11ea-99ff-bef679e587c4.PNG)

How does this look?

**Comment by mcourtot** [comment]
Really nice! 
Small comment - if easy to do can we get read of the double precision, e.g. 28% instead of 28.85%?  really not a major issue, I think that woudl fall under minor minor one, so not a concern.

**Comment by dipayan1985** [comment]
![bar](https://user-images.githubusercontent.com/55179939/81553255-b62f4380-937c-11ea-9209-be4b6a560798.PNG)

This is done.
