### ISSUE TITLE
Certain file name formats cause validation to fail

### ISSUE THREAD

**Issue by z-w123** [ebi-ait/sars-cov2-data-upload#22]
From Nadim:

A file with a ‘.’ in the middle of the name fails validation on file type, regardless of whether it has an accepted format ending.
E.g. CAMB-73D89.20200407_1713_X2_FAN41688_045eb5a8.climb.public.bam is not accepted, but CAMB-73D89_20200407_1713_X2_FAN41688_045eb5a8_climb_public.bam is.
This is an example of a real file name (often these are created in automated fashion) and should be accepted - note this file name is accepted by current Webin submission services.

**Comment by dipayan1985** [comment]
Addressed and closed. Thanks for reporting.
