### ISSUE TITLE
Error when submitting files with md5 at the end of file name (using Webin-CLI) 

### ISSUE THREAD

**Issue by z-w123** [ebi-ait/sars-cov2-data-upload#23]
From Nadim:

It is better for downstream processes, if the md5s are saved in a file as opposed to additionally tagged on the data file name.
E.g. If a user submits a file **- file_1.fastq.gz,** the upload tool creates a separate file for this, housing just the md5 value for the data file called **file_1.fastq.gz.md5.**
This is because it adds a separate step to extract the checksums from the filenames and create the corresponding md5 file. The data file(s) must end with fastq.gz, .bam or .cram for it to then be submitted by the user support bioinformatician with Webin-CLI.

**Comment by mcourtot** [comment]
Hi @z-w123 and @nadimm-rahman 

@dipayan1985 explained that with the current application it is impossible to generate files - adding the md5 in the filename was the only way at this stage to handle the need for md5. 

We'll look at other way to do this once the application is ported to Embassy, this will take a couple weeks.
