### ISSUE TITLE
md5 value mismatch

### ISSUE THREAD

**Issue by alisha246** [ebi-ait/sars-cov2-data-upload#28]
The md5 values attached to file names generated after uploading files via COVID uploader tool do not match with the exact md5 values pre and post upload. It seems like the md5 value in the generated file name is incorrect. Please see below 2 different examples.

**Example 1:**

**Filename generated with md5 after upload via COVID uploader tool:**
ERR3858930_R1.fastq.gz.a6fcfe37184c4a2162ecd6b51b36de09

**md5 value of the file pre upload:**
d651ff2a93b102eae0d67d545a5e6536  ERR3858930_R1.fastq.gz

**md5 value of the file post upload:**
d651ff2a93b102eae0d67d545a5e6536  ERR3858930_R1.fastq.gz.a6fcfe37184c4a2162ecd6b51b36de09

**Example 2:**

**Filename generated with md5 after upload via COVID uploader tool:**
ATT26.mappedHs37.trim2.bam.fce6ee50d3abca1a0aa468f24bb0b39c

**md5 value of the file pre upload:**
bfd2c023fcf1cfbc6a9560f0a1f6a8f9  ATT26.mappedHs37.trim2.bam

**md5 value of the file post upload:**
bfd2c023fcf1cfbc6a9560f0a1f6a8f9  ATT26.mappedHs37.trim2.bam.fce6ee50d3abca1a0aa468f24bb0b39c

@nadimm-rahman 
@z-w123 
@Jeena-Rajan

**Comment by z-w123** [comment]
@alisha246  I encountered the same issue during testing of the tool

**Comment by dipayan1985** [comment]
@alisha246 @z-w123,

MD5 hash is a API generated value. The covid-uploader doesn't know about the pre-upload MD5 and generates a completely new hash. It is not impossible to use the pre-upload MD5 if there is always a fixed naming pattern. I have a couple of questions related to this:

1. Do all files (except metadata files) have a pre-upload MD5?
2. Is there a naming convention? The 2 examples you have given has MD5 FILENAME.extension pattern.

3. If 1 and 2 above are both 'yes' then we can do the changes and you can upload files with MD5 appended at the file name, like the pre-upload file names in your examples. 

Thanks,
Dipayan

/cc @mcourtot , @Jeena-Rajan

**Comment by mcourtot** [comment]
Hi @dipayan1985 - I'm not sure what you mean. Shouldn't the same file, using the same md5 hashing algorithm, give the same result?

i.e. 
user generate md5 on file A -> md5 value bfd2c023fcf1cfbc6a9560f0a1f6a8f9 
user uploads file on covid uploader
ENA receives file and generates md5 to check -> should return same value bfd2c023fcf1cfbc6a9560f0a1f6a8f9 

so I would expect the uploader to create a file called fileA.gz.bfd2c023fcf1cfbc6a9560f0a1f6a8f9

**Comment by mcourtot** [comment]
@dipayan1985 clarified that the md5 currently being computed is on the file name rather than the file content.
The latter is not currently supported with the current architecture but can be flagged as future feature requirement.

**Comment by Jeena-Rajan** [comment]
@mcourtot and @dipayan1985, we need to be able to verify the integrity of the file post upload which the current md5 is not doing. Is there an ETA for this?  We have requested the tool is shown on the COVID portal and the md5 (for file integrity) issue becomes important if we get use of the tool. The current md5 appended to the filename is not useful and we can't use this so probably best to remove this. Thanks

**Comment by dipayan1985** [comment]
@Jeena-Rajan 
We have got the MD5 hash on file working. We have not deployed it in production but will put it in soon.

/cc @mcourtot

**Comment by Jeena-Rajan** [comment]
Great, thanks @dipayan1985

**Comment by dipayan1985** [comment]
@z-w123 

I have re-deployed the changes and its ready to test.

/cc @mcourtot

**Comment by z-w123** [comment]
@alisha246 @dipayan1985 we can confirm that the md5 value of the file pre and post upload now matches the one appended to the end of the file name. Thanks!

**Comment by dipayan1985** [comment]
Closing as this is fixed.
