### ISSUE TITLE
Add covid portal favicons

### ISSUE THREAD

**Issue by mcourtot** [ebi-ait/sars-cov2-data-upload#31]
[cv19portal-favicon.zip](https://github.com/ebi-ait/sars-cov2-data-upload/files/5000510/cv19portal-favicon.zip)

From @peterwharrison 
> For consistency it would be great if your developers can update the covid drag and drop tool to use the COVID portal favicons.
> In the zip you will find a favicon folder with images and config, while in index.html the meta information to add.
> In index.html paths need to be adapted to where you place the content of the favicon folder.

cc @guycochrane @z-w123 @Jeena-Rajan

**Comment by dipayan1985** [comment]
@z-w123
Hi Zahra,

This change related to the favicon icon of the uploader is completed. If it is OK this can be deployed with the other changes on Monday?

Thanks.,
Dipayan

/cc @mcourtot
