### ISSUE TITLE
SARS-CoV-2 Data Hubs Logo on uploader page redirects to https://ebi-ait.github.io/ 

### ISSUE THREAD

**Issue by z-w123** [ebi-ait/sars-cov2-data-upload#32]
A bug has been identified on the covid uploader page: https://ebi-ait.github.io/sars-cov2-data-upload/ where clicking on the 'SARS-CoV-2 Data Hubs' logo redirects to this URL https://ebi-ait.github.io/

Would be good if this URL can be replaced with: https://www.covid19dataportal.org/ so that clicking on the logo redirects to the main covid-19 data portal instead. 

@Jeena-Rajan @nadimm-rahman

**Comment by dipayan1985** [comment]
@z-w123 
Hi Zahra,

This change is completed. Is it OK to do a deployment on Monday (August 10)?

Thanks.,
Dipayan

/cc @mcourtot

**Comment by z-w123** [comment]
Hi Dipayan,
that would be great, thanks

**Comment by dipayan1985** [comment]
@z-w123 
Deployment completed.
As a safety measure I monitored the S3 logs while deployment and found no PUT/POST and hence no user impact while deployment was being done.
/cc @mcourtot
