### ISSUE TITLE
Uploader tool to support gzipped .fasta, .embl and .txt file formats for genome assembly submission

### ISSUE THREAD

**Issue by z-w123** [ebi-ait/sars-cov2-data-upload#33]
Many users submit small-scale genome assemblies, and in terms of file size, these would be ideal volunteers to test the uploader tool. Therefore it would be very useful to have .fasta.gz, .embl.gz and .txt.gz data file formats accepted by the tool, to additionally support the submission of genome assemblies.

As with read file submission, the .md5 values would be appended to the end of the .fasta.gz/.embl.gz/.txt.gz file name.

cc @Jeena-Rajan @nadimm-rahman

**Comment by dipayan1985** [comment]
File formats added. Good to go in the next release.

**Comment by z-w123** [comment]
Thanks @dipayan1985 !
