### ISSUE TITLE
Include a user field for Webin-ID in tool login page

### ISSUE THREAD

**Issue by z-w123** [ebi-ait/sars-cov2-data-upload#34]
As a single user can have several Webin ID's, and a single Webin account can have multiple contact emails listed, it would be really useful to have a user-field for Webin-ID in the login page: https://ebi-ait.github.io/sars-cov2-data-upload/ , so that the user can specify which account to submit their data to.

This is instead of the current method which pulls the Webin-ID.

cc @nadimm-rahman @Jeena-Rajan 

Many thanks,

**Comment by dipayan1985** [comment]
@z-w123 
Hi Zahra, I was OOO for few days and hence the delay in looking into it. I will try to do it asap and let you know,

**Comment by z-w123** [comment]
@dipayan1985 no problem, thank you

**Comment by dipayan1985** [comment]
@z-w123 I have done the changes now and will deploy it on Friday. I have not made Webin-ID as a mandatory field because it will be restrictive for a new submitter who doesn't have a Webin account. Does that sound OK to you?

/cc @clairerye

**Comment by z-w123** [comment]
@dipayan1985 that sounds good - we should be able to generate the Webin-ID as part of the back end. Thanks !

**Comment by dipayan1985** [comment]
@z-w123 
This is done now and deployed, please retest and let us know if you find any issues.

/cc @clairerye
