### ISSUE TITLE
Possible redirection to Webin portal for users not registered in WEBIN

### ISSUE THREAD

**Issue by dipayan1985** [ebi-ait/sars-cov2-data-upload#35]
Hi, @z-w123 @nadimm-rahman @ahmadazd

I am not able to tag Ahmad to this ticket. Could you please if you have his GitHub Id?

This is regarding the handling of users who doesn't have a WEBIN account. As per the SOP, you will be creating WEBIN accounts for such users. To make this process automated I was thinking of adding a possible redirection to WEBIN Portals user registration page.

Suggestions are welcome.

/cc @clairerye @MightyAx @ke4

**Comment by ahmadazd** [comment]
Thanks @dipayan1985. well received

**Comment by z-w123** [comment]
Thanks @dipayan1985 - I also think this will be very helpful for our users. Do you plan to link to the registration page of interactive webin?  https://www.ebi.ac.uk/ena/submit/sra/#registration

**Comment by dipayan1985** [comment]
@z-w123 yes the redirection will be to the registration page of interactive WEBIN. We will try to get this change released in production by mid of next week.

**Comment by dipayan1985** [comment]
Hi @z-w123 I am done with the changes for this but unfortunately GH pages is not accepting a new deployment. Expected this issue will get resolved this week and we will be able to push changes to prod.

**Comment by z-w123** [comment]
Sure, thank you for the update

**Comment by dipayan1985** [comment]
This is ready to be deployed now. GH pages only recently got fixed and accepting new deployment. I will let you know once this is done. /cc @z-w123

**Comment by dipayan1985** [comment]
Deployed /cc @z-w123
