### ISSUE TITLE
Capture Webin User from drag-and-drop into embassy VM

### ISSUE THREAD

**Issue by dipayan1985** [ebi-ait/sars-cov2-data-upload#37]
https://trello.com/c/9mD9Joig/54-capture-webin-user-from-drag-and-drop-into-embassy-vm

Prepend WEBIN_ID with metadata spreadsheet name.

/cc @z-w123, @MightyAx, @clairerye, @ke4

**Comment by dipayan1985** [comment]
Deployed /cc @MightyAx

**Comment by z-w123** [comment]
Hi Dipayan,
I don't have access to the trello board - but I understand it's probably 
for internal use within your team.
I understand this task is related to ENA brokering?

Thank you.

Kind regards,
Zahra

**Comment by dipayan1985** [comment]
@z-w123 Hi Zahra - I missed this comment from you. 
Yes it is right, we need the Webin-ID to be able to broker the data files to ENA and if the Webin-ID can be captured from the drag'n'drop then with super user password the files can be transferred to Webin FTP.

**Comment by z-w123** [comment]
understood - thank you @dipayan1985 !👍
