### ISSUE TITLE
Add 'submission' tab at top of page

### ISSUE THREAD

**Issue by mcourtot** [ebi-ait/sars-cov2-data-upload#5]
https://ebi-ait.github.io/sars-cov2-data-upload/app-documentation has a link at the top towards 'documentation' - should we add a tab 'submission'? the only other way to go back is otherwise at the bottom of the page.

**Comment by dipayan1985** [comment]
Added submission link.
@mcourtot - We need to find a deployment window for these new changes. I will do all changes and then may be we deploy all together at once. When we deploy we should be sure that no one is using the UI for uploads because the uploads will be terminated immediately.

**Comment by mcourtot** [comment]
do you know how long the deployment takes approximately?

**Comment by mcourtot** [comment]
is there an option to have a second server and just bounce to this one (I suspect not possible once the upload started in one client, but just to confirm)

**Comment by dipayan1985** [comment]
The deployment time is approx 20 mins.

There is not much flexibility of having a second server in GH pages, URL will be different and load balancer setup is not supported. I will think of something that will not be disruptive.

**Comment by mcourtot** [comment]
if we were able to deploy on 2 EBI VMs, would there still be interruption of uploads as the load balancer redirects to the other VM? 

eg I start the upload through VM1, then we take VM1 down for update, the load balancer sends me to VM2 - will that reinitialise all my work?

**Comment by dipayan1985** [comment]
Yes is there is a load balancer setup, everything should be fine.
