### ISSUE TITLE
Final message post 'submit'

### ISSUE THREAD

**Issue by mcourtot** [ebi-ait/sars-cov2-data-upload#9]
the message reads "Notification sent for your submission. You will receive a notification..." which is unclear. Should we instead say something like "Thank you for your submission!"?

<img width="1011" alt="Screenshot 2020-04-30 at 12 49 21" src="https://user-images.githubusercontent.com/2214135/80706956-169ec500-8ae1-11ea-8b62-c0b14e818bd8.png">

**Comment by mcourtot** [comment]
Proposed new message:

Submission complete. You will hear from the team by email within 2 working days, either with questions relating to data validation or with confirmation of successful submission and advice on accession numbers.

cc @guycochrane @jeena-rajan

**Comment by dipayan1985** [comment]
This is updated now. Not deployed in GH pages yet.
